### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mercadopago/px_tracking/MPTracker;

### ISSUE THREAD

**Issue by Alfishan** [mercadopago/px-android#722] opened 2017-11-01 06:44 UTC
![screenshot from 2017-11-01 12-15-34](https://user-images.githubusercontent.com/19745182/32263195-b3309e7c-befe-11e7-84c2-45c8de9988b7.png)
Getting java.lang.NoClassDefFoundError exception after implementing on API level 26 Enabled  multiDex  

`FATAL EXCEPTION: main
                                                                     Process: xeme.dragondrinks.debug, PID: 939
                                                                     java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mercadopago/px_tracking/MPTracker;
                                                                         at com.mercadopago.CheckoutActivity.initializeMPTracker(CheckoutActivity.java:135)
                                                                         at com.mercadopago.presenters.CheckoutPresenter.startCheckoutForPreference(CheckoutPresenter.java:108)
                                                                         at com.mercadopago.presenters.CheckoutPresenter.initialize(CheckoutPresenter.java:96)
                                                                         at com.mercadopago.CheckoutActivity.onCreate(CheckoutActivity.java:75)
                                                                         at android.app.Activity.performCreate(Activity.java:6679)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                         at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                      Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mercadopago.px_tracking.MPTracker" on path: DexPathList[[zip file "/data/app/xeme.dragondrinks.debug-1/base.apk"],nativeLibraryDirectories=[/data/app/xeme.dragondrinks.debug-1/lib/x86, /data/app/xeme.dragondrinks.debug-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
                                                                         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                         at com.mercadopago.CheckoutActivity.initializeMPTracker(CheckoutActivity.java:135) 
                                                                         at com.mercadopago.presenters.CheckoutPresenter.startCheckoutForPreference(CheckoutPresenter.java:108) 
                                                                         at com.mercadopago.presenters.CheckoutPresenter.initialize(CheckoutPresenter.java:96) 
                                                                         at com.mercadopago.CheckoutActivity.onCreate(CheckoutActivity.java:75) 
                                                                         at android.app.Activity.performCreate(Activity.java:6679) 
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618) 
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                                         at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:154) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) `

**Comment by mreverter** [comment] 2017-11-02 14:32
Hi! Which MercadoPago SDK version are you using?

**Comment by Alfishan** [comment] 2017-11-03 05:43
Thanks for replying. I am using 3.7.0 as per document.

**Comment by ederpadilla** [comment] 2017-11-03 19:00
Same issue at 3.7.0 
 FATAL EXCEPTION: main
                                                                  Process: mx.drivepp.drive, PID: 26845
                                                                  java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mercadopago/px_tracking/MPTracker;
                                                                      at com.mercadopago.adapters.ErrorHandlingCallAdapter$MPCallAdapter$1$1.run(ErrorHandlingCallAdapter.java:91)
                                                                      at android.os.Handler.handleCallback(Handler.java:751)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6692)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
                                                                   Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mercadopago.px_tracking.MPTracker" on path: DexPathList[[zip file "/data/app/mx.drivepp.drive-1/base.apk"],nativeLibraryDirectories=[/data/app/mx.drivepp.drive-1/lib/arm64, /data/app/mx.drivepp.drive-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
                                                                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                      at com.mercadopago.adapters.ErrorHandlingCallAdapter$MPCallAdapter$1$1.run(ErrorHandlingCallAdapter.java:91) 
                                                                      at android.os.Handler.handleCallback(Handler.java:751) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                      at android.os.Looper.loop(Looper.java:154) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6692) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by zehemz** [comment] 2018-09-28 00:39
Hi, resolved in version 4.+
Thanks.

**Closed by zehemz** 2018-09-28 00:39 UTC
